language: c++
compiler: gcc
dist: precise

addons:
  apt:
    packages:
      - libboost-graph-dev
      - doxygen
      - texlive
      - texlive-formats-extra
      - texlive-fonts-extra
      - lmodern
      - latex2html

script:
  - autoreconf -si
  - ./configure
  - make -j
  - make pdf -j
  - make html
