language: cpp
compiler: gcc
dist: trusty

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install g++-6 -y
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

addons:
  apt:
    packages:
      - libboost-graph-dev
      - doxygen
      - texlive
      - texlive-formats-extra
      - texlive-fonts-extra
      - lmodern
      - latex2html

branches:
  only:
  - master

git:
  depth: false

script:
  - autoreconf -si
  - ./configure
  - make -j
  - make pdf -j
  - make html
